import React, { useState, useEffect } from "react";
import DeleteIcon from "@mui/icons-material/Delete";
import AddIcon from "@mui/icons-material/Add";
import {
  Alert,
  Button,
  Card,
  CardContent,
  Grid,
  Snackbar,
  TextField,
  Select,
  Box,
  MenuItem,
} from "@mui/material";
import { useForm, Controller, useFieldArray } from "react-hook-form";
import axios from "axios";
import { useDispatch } from "react-redux";
import { GET_CURRENT_USER } from "../actions/types";
import { UNITS } from "../CONSTANTS";

function RecipeCreateForm({ defaultValues, title }) {
  const dispatch = useDispatch();

  const { control, handleSubmit, reset } = useForm({
    name: defaultValues?.name,
    ingredients: defaultValues?.ingredients,
    instructions: defaultValues?.instructions,
  });
  const { fields, append, remove } = useFieldArray({
    name: "ingredients",
    defaultValue: defaultValues?.ingredients,
    control,
  });
  const [displaySnackbar, setOpenSnackbar] = useState(false);
  const [sendSuccess, setSendSuccess] = useState(false);
  const [ingredientCount, setIngredientCount] = useState(
    defaultValues?.ingredients?.length || 1
  );

  const resetForm = () => {
    //set number of ingredients to correct length
    console.log("ingredientCount: ", ingredientCount);
    console.log("default length: ", defaultValues?.ingredients?.length);
    setIngredientCount(1);
    console.log("ingredientCount: ", ingredientCount);
    reset();
  };

  const onSubmit = async (data) => {
    //clean ingredients and instructions lists to be [String]
    console.log("SUBMITTED DATA FROM FORM: ", data);
    const instructions = data.instructions
      .split("\n")
      .filter((str) => str !== "");
    const newRecipe = {
      name: data.name,
      ingredients: data.ingredients,
      instructions,
      _id: defaultValues?._id,
    };
    const res = await axios.post("/api/recipe", newRecipe);
    dispatch({ type: GET_CURRENT_USER, payload: res.data });
    if (res.status === 200) {
      setSendSuccess(true);
    } else {
      setSendSuccess(false);
    }
    setOpenSnackbar(true);
    if (title.toUpperCase() === "CREATE") {
      reset();
    }
  };

  useEffect(() => {
    console.log("useEffect");
    console.log("default length", defaultValues?.ingredients?.length);
    console.log("fields length", fields.length);
    if (defaultValues?.ingredients?.length > fields.length) {
      defaultValues?.ingredients?.forEach(() => {
        append({});
      });
      remove(-1); //removes the extra empty ingredient generated by above for loop
    }
    if (ingredientCount > fields.length) {
      append({});
    }
    console.log("after", fields.length);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ingredientCount, defaultValues]);

  return (
    <>
      <Card raised>
        <CardContent>
          <h2>{title} a Recipe</h2>
          <form onSubmit={handleSubmit(onSubmit)}>
            <Grid container rowSpacing={2} columnSpacing={{ xs: 1, sm: 2 }}>
              <Grid item xs={12}>
                <h4>Recipe Name</h4>
                <Controller
                  name="name"
                  control={control}
                  defaultValue={defaultValues?.name}
                  render={({ field }) => (
                    <TextField
                      {...field}
                      placeholder="Enter recipe name"
                      variant="outlined"
                      sx={{ width: "100%" }}
                      required
                    />
                  )}
                />
              </Grid>

              <Grid
                container
                item
                rowSpacing={2}
                columnSpacing={{ xs: 1, sm: 2 }}
              >
                <Grid item xs={12}>
                  <Box
                    sx={{ display: "flex", justifyContent: "space-between" }}
                  >
                    <h4>Ingredients</h4>
                    <Button
                      variant="contained"
                      color="success"
                      sx={{
                        height: "24px",
                        width: "24px",
                      }}
                      onClick={() => {
                        setIngredientCount(ingredientCount + 1);
                      }}
                    >
                      <AddIcon />
                    </Button>
                  </Box>
                </Grid>
                {fields.map((item, i) => (
                  // key must be item.id and remove must use i
                  //in order to properly remove the ingredient from the list
                  <React.Fragment key={item.id}>
                    <Grid item xs={6} sm={2}>
                      <Controller
                        name={`ingredients[${i}].quantity`}
                        defaultValue={
                          defaultValues?.ingredients[i]
                            ? defaultValues.ingredients[i]?.quantity
                            : ""
                        }
                        control={control}
                        render={({ field }) => (
                          <TextField
                            {...field}
                            type="number"
                            placeholder="Enter quantity"
                            variant="outlined"
                            sx={{ width: "100%" }}
                          />
                        )}
                      />
                    </Grid>
                    <Grid item xs={3} sm={2}>
                      <Controller
                        name={`ingredients[${i}].unit`}
                        defaultValue={
                          defaultValues?.ingredients[i]
                            ? defaultValues.ingredients[i]?.unit
                            : ""
                        }
                        control={control}
                        render={({ field }) => (
                          <Select {...field} sx={{ width: "100%" }}>
                            {UNITS.map((unit) => (
                              <MenuItem key={unit} value={unit}>
                                {unit}
                              </MenuItem>
                            ))}
                          </Select>
                        )}
                      />
                    </Grid>
                    <Grid item xs={12} sm={7}>
                      <Controller
                        name={`ingredients[${i}].name`}
                        defaultValue={
                          defaultValues?.ingredients[i]
                            ? defaultValues.ingredients[i]?.name
                            : ""
                        }
                        control={control}
                        render={({ field }) => (
                          <TextField
                            {...field}
                            placeholder="Enter name"
                            variant="outlined"
                            sx={{ width: "100%" }}
                            required
                          />
                        )}
                      />
                    </Grid>
                    <Grid item xs={3} sm={1}>
                      <Button
                        onClick={() => remove(i)}
                        variant="outlined"
                        color="error"
                        sx={{ marginTop: "0.75em" }}
                      >
                        <DeleteIcon />
                      </Button>
                    </Grid>
                  </React.Fragment>
                ))}
              </Grid>

              <Grid item xs={12}>
                <h4>Instructions</h4>
                <Controller
                  name="instructions"
                  defaultValue={defaultValues?.instructions?.join("\n")}
                  control={control}
                  render={({ field }) => (
                    <TextField
                      {...field}
                      placeholder="Enter instructions"
                      variant="outlined"
                      sx={{ width: "100%" }}
                      multiline
                      minRows={5}
                      required
                    />
                  )}
                />
              </Grid>
              <Grid item xs={12}>
                {/* <Button variant="outlined" color="warning" onClick={resetForm}>
                  Reset
                </Button> */}
                <Button variant="contained" color="success" type="submit">
                  Confirm
                </Button>
              </Grid>
            </Grid>
          </form>
        </CardContent>
      </Card>
      <Snackbar
        open={displaySnackbar}
        autoHideDuration={4000}
        onClose={() => setOpenSnackbar(false)}
      >
        {sendSuccess ? (
          <Alert
            onClose={() => setOpenSnackbar(false)}
            severity="success"
            sx={{ width: "100%" }}
          >
            Recipe successfully saved
          </Alert>
        ) : (
          <Alert
            onClose={() => setOpenSnackbar(false)}
            severity="error"
            sx={{ width: "100%" }}
          >
            Error saving recipe!
          </Alert>
        )}
      </Snackbar>
    </>
  );
}

export default RecipeCreateForm;
